spring:
  application:
    name: keycloak
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/yers__check
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/yers__check
            user-name-attribute: preferred_username
        registration:
          keycloak:
            client-id: springsecurity
            client-secret: jYSlESWbkYzwhGIkld811YCr77Tr1koI
            scope: openid

server:
  port: 8081

keycloak:
  auth-server-url: http://localhost:8080
  realm: yers__check

  # oauth2-login / resource-server client
  client-id: springsecurity
  client-secret: jYSlESWbkYzwhGIkld811YCr77Tr1koI

  # credentials для admin CLI (используется в KeycloakUserService#getAdminAccessToken)
  admin:
    client-id: springsecurity
    client-secret: jYSlESWbkYzwhGIkld811YCr77Tr1koI
